version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-container
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  server:
    build: ./server
    image: node-server
    container_name: node-server-container
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
  web:
    build: ./web
    image: react-web
    container_name: react-web-container
    ports:
      - 3000:80
    volumes:
      - ./web:/web

volumes:
  postgres-data:
  pgadmin-data:


